/**
 * RTOS project templates - shared between web and desktop versions.
 */

const zephyrCMake = (name) => `cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(${name})

target_sources(app PRIVATE src/main.c)
`;

const zephyrConf = `# Application Kconfig
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

# Stack and thread defaults
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
`;

const zephyrMain = `#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>

int main(void)
{
    printk("Zephyr firmware starting on %s\\n", CONFIG_BOARD);

    while (1) {
        printk("tick\\n");
        k_sleep(K_SECONDS(1));
    }

    return 0;
}
`;

const freeRTOSCMake = (name) => `cmake_minimum_required(VERSION 3.20.0)
project(${name} C CXX ASM)

set(CMAKE_C_STANDARD 11)

# FreeRTOS configuration
set(FREERTOS_CFG_DIRECTORY    "\${CMAKE_CURRENT_SOURCE_DIR}/src")
set(FREERTOS_SOURCE_DIRECTORY "\${CMAKE_CURRENT_SOURCE_DIR}/third_party/FreeRTOS-Kernel")

include_directories(
    "\${FREERTOS_CFG_DIRECTORY}"
    "\${FREERTOS_SOURCE_DIRECTORY}/include"
    "\${FREERTOS_SOURCE_DIRECTORY}/portable/GCC/ARM_CM4F"
)

add_executable(\${PROJECT_NAME}
    src/main.c
    \${FREERTOS_SOURCE_DIRECTORY}/tasks.c
    \${FREERTOS_SOURCE_DIRECTORY}/queue.c
    \${FREERTOS_SOURCE_DIRECTORY}/list.c
    \${FREERTOS_SOURCE_DIRECTORY}/timers.c
    \${FREERTOS_SOURCE_DIRECTORY}/portable/MemMang/heap_4.c
    \${FREERTOS_SOURCE_DIRECTORY}/portable/GCC/ARM_CM4F/port.c
)

target_compile_definitions(\${PROJECT_NAME} PRIVATE FREERTOS_CONFIG_H)
`;

const freeRTOSTemplate = `#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include <stdio.h>

static StaticTask_t xTaskBuffer;
static StackType_t xStack[configMINIMAL_STACK_SIZE];
static TaskHandle_t xHandle;

static void vMainTask(void *pvParameters)
{
    (void)pvParameters;
    for (;;) {
        printf("FreeRTOS tick\\n");
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}

int main(void)
{
    xHandle = xTaskCreateStatic(
        vMainTask,
        "main",
        configMINIMAL_STACK_SIZE,
        NULL,
        tskIDLE_PRIORITY + 1,
        xStack,
        &xTaskBuffer);

    vTaskStartScheduler();

    /* Should never reach here. */
    for (;;) {
    }
}
`;

const freeRTOSConfig = `#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

#include <stdint.h>

#define configUSE_PREEMPTION                    1
#define configUSE_IDLE_HOOK                     0
#define configUSE_TICK_HOOK                     0
#define configCPU_CLOCK_HZ                      ((uint32_t)168000000)
#define configTICK_RATE_HZ                      ((TickType_t)1000)
#define configMAX_PRIORITIES                    (5)
#define configMINIMAL_STACK_SIZE                ((uint16_t)128)
#define configTOTAL_HEAP_SIZE                   ((size_t)(16 * 1024))
#define configMAX_TASK_NAME_LEN                 (16)
#define configUSE_TRACE_FACILITY                0
#define configUSE_16_BIT_TICKS                  0
#define configIDLE_SHOULD_YIELD                 1
#define configUSE_MUTEXES                       1
#define configQUEUE_REGISTRY_SIZE               8
#define configCHECK_FOR_STACK_OVERFLOW          2
#define configUSE_RECURSIVE_MUTEXES             1
#define configUSE_MALLOC_FAILED_HOOK            1
#define configUSE_APPLICATION_TASK_TAG          0
#define configUSE_COUNTING_SEMAPHORES           1
#define configSUPPORT_STATIC_ALLOCATION         1
#define configSUPPORT_DYNAMIC_ALLOCATION        0

#define configKERNEL_INTERRUPT_PRIORITY         (255)
#define configMAX_SYSCALL_INTERRUPT_PRIORITY    (191)

#include "stdlib.h"
void vAssertCalled(const char *file, unsigned long line);
#define configASSERT(x) if ((x) == 0) vAssertCalled(__FILE__, __LINE__)

#endif /* FREERTOS_CONFIG_H */
`;

function makeSkeleton(rtos, name) {
  const base = [
    {
      path: "CMakeLists.txt",
      content: rtos === "zephyr" ? zephyrCMake(name) : freeRTOSCMake(name),
      type: "cmake",
    },
    {
      path: "src/main.c",
      content: rtos === "zephyr" ? zephyrMain : freeRTOSTemplate,
      type: "c",
    },
    {
      path: "README.md",
      content: `# ${name}\n\nEmbedded firmware project generated by EmbedFactory.\n\n- RTOS: ${rtos === "zephyr" ? "Zephyr" : "FreeRTOS"}\n- Build: CMake\n\n## Build\n\n${rtos === "zephyr" ? "west build -b <board> -p auto" : "mkdir build && cd build && cmake .. && make"}\n`,
      type: "md",
    },
  ];

  if (rtos === "zephyr") {
    base.push({ path: "prj.conf", content: zephyrConf, type: "conf" });
  } else {
    base.push({ path: "src/FreeRTOSConfig.h", content: freeRTOSConfig, type: "h" });
  }

  return base;
}

module.exports = { makeSkeleton, inferFileType: require("./db").inferFileType };
